### ISSUE TITLE
OSEP 8: introduce "current session" logic

### ISSUE THREAD

**Issue by jamesturk** [openstates/enhancement-proposals#29]
planning a small OSEP for this, but wanted to kick around ideas first

Right now when os-update runs, it only runs on the last session in the metadata.

I'd like to change that to have it run for all 'active' sessions by default.  The logic would look something like:

- Use the begin & end dates to determine which sessions are active. 
- Print the sessions to be scraped (as it does now) for clarity.
- It'd then run the scraper multiple times, once per active session.
- The  output JSON would all be in the same directory.

If an argument like `session=2021B` was passed, that would supersede this behavior (as it does now).

This would allow us to avoid situations where a state is simultaneously updating their regular and one or more special sessions.

I think it'd have minimal impact on runtime since most specials take <30 mins. 

Any concerns?  Things I'm possibly forgetting?

The other idea would be to add a `current` flag to the metadata, but that'd require more active management & I figure begin & end dates are a decent proxy for this.

**Comment by jamesturk** [comment]
Immediately realized one caveat, the end dates are often in the past, which would lead to nothing being run.   If there are no 'active' sessions, the latest one in the file could be used, essentially falling back to the current behavior.

**Comment by jamesturk** [comment]
cc @showerst @jessemortenson

**Comment by showerst** [comment]
Dates tend to be so wonky with legislatures, and since we're manually adding new sessions anyway i'd be strongly in favor of the "current" flag in the metadata.

Some sample cases i'm thinking where dates are a pain:

- IL governor sometimes signs bills from the previous session even after the new one started, this year I think that happened as late as march 2022 after 2021 regular session close. 
- Sometimes a session has passed and it's truly closed by law, so we're just wasting cycles scraping it. 
- Often (a majority of the time?) a regular is truly closed, but the special isn't. So now we're scraping thousands of unneeded bills to get to the special content.
- How would it work for prefiles? Just scrape all future sessions?
- Oftentimes executive deadlines have no relation to session dates

I think that the inevitable "Oops I forgot to go flip the boolean on the old session when I added the new one" bugs are easier to fix and debug then the "Why did i commit but my session didn't scrape?" or "Why is this scrape taking four hours and the 'HB 123' it emitted isn't the one I want" ? issues.

I'll admit that this approach does raise the barrier to entry for new contributors, but I think I'd be fine w/ someone submitting a patch that doesn't disable scraping older sessions and we have to add that at a later date.

Overall it's a good idea though, it will be nice to avoid configuring duplicate tasks for scraping old and new, and make everybody's knowledge of the state of what should be getting collected more explicit from this repo.

**Comment by showerst** [comment]
A good test case right now is VA, at least as of a few days ago -- 

1. The Regular is getting updates from the executive/SoS. It's past it's "end date" in the sense that the legislature is not sitting for it
2. Special 1 is legally finished.
3. Special 2 is in progress normally.

So here we want to flag [1,3] to be scraped, but only the third case is "in" if you're asking what the current session is, or want to highlight a map or whatever.

**Comment by jamesturk** [comment]
Thanks for pointing out these edge cases, this makes a lot of sense & I'm won over that the current flag is better than trying to automate guessing after all.  (I'd really mainly been considering the case where the only thing being scraped unnecessarily was a special session, but the examples above make sense & I'll borrow them for the OSEP)

**Comment by jamesturk** [comment]
just opened up #30 with a version of this that relies upon an `active` flag
